[package]
name = "opendotgit"
author = "Himadri Bhattacharjee <lavafroth@protonmail.com>"
about = "Dump git repository from open .git directories"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
color-eyre = "0.6.2"
regex = "1.7.1"
reqwest = { version = "0.11", features = ["socks"] }
soup = "0.5.1"
tokio = { version = "1", features = ["full"] }
url = "2.3.1"
url_path = "0.1.3"
