[package]
name = "opendotgit"
author = "Himadri Bhattacharjee <lavafroth@protonmail.com>"
about = "Dump git repository from open .git directories"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
clap = { version = "4.1.4", features = ["derive"] }
color-eyre = "0.6.2"
flate2 = "1.0.26"
futures = "0.3.26"
git-features = "0.26.5"
git2 = "0.17.1"
gix-pack = "0.35.0"
hex = "0.4.3"
hyper = {version = "0.14.24", features = ["full"]}
hyper-tls = "0.5.0"
miniz_oxide = "0.7.1"
regex = "1.7.1"
ring = "0.16.20"
soup = "0.5.1"
tokio = { version = "1", features = ["full"] }
url = "2.3.1"
url_path = "0.1.3"
walkdir = "2.3.2"
