/// A slice of file paths that are commonly found in Git repositories.
pub static KNOWN_FILES: &[&str] = &[
    ".gitignore",
    ".git/COMMIT_EDITMSG",
    ".git/description",
    ".git/hooks/applypatch-msg.sample",
    ".git/hooks/commit-msg.sample",
    ".git/hooks/post-commit.sample",
    ".git/hooks/post-receive.sample",
    ".git/hooks/post-update.sample",
    ".git/hooks/pre-applypatch.sample",
    ".git/hooks/pre-commit.sample",
    ".git/hooks/pre-push.sample",
    ".git/hooks/pre-rebase.sample",
    ".git/hooks/pre-receive.sample",
    ".git/hooks/prepare-commit-msg.sample",
    ".git/hooks/update.sample",
    ".git/index",
    ".git/info/exclude",
    ".git/objects/info/packs",
];

/// A slice of file paths that reference various locations within a Git repository.
pub static REF_FILES: &[&str] = &[
    ".git/FETCH_HEAD",
    ".git/HEAD",
    ".git/ORIG_HEAD",
    ".git/config",
    ".git/info/refs",
    ".git/logs/HEAD",
    ".git/logs/refs/heads/master",
    ".git/logs/refs/remotes/origin/HEAD",
    ".git/logs/refs/remotes/origin/master",
    ".git/logs/refs/stash",
    ".git/packed-refs",
    ".git/refs/heads/master",
    ".git/refs/remotes/origin/HEAD",
    ".git/refs/remotes/origin/master",
    ".git/refs/stash",
    ".git/refs/wip/wtree/refs/heads/master",
    ".git/refs/wip/index/refs/heads/master",
];
